## database ##
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blogserver
    username: your_name
    password: your_password
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: your_password
      database: 0


##  mybatis配置  ##
mybatis:
  mapper-locations: classpath:mapper/*Mapper;
  type-aliases-package: top.hastur23.blogServer.entity;
  configuration:
    map-underscore-to-camel-case: true

## 服务器配置  ##
server:
  port: 8088