## database ##
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogserver?useUnicode=true&characterEncoding=utf8
    username: hastur23
    password: Shikuc166017
    driver-class-name: com.mysql.cj.jdbc.Driver